Make code PY_SSIZE_T_CLEAN
Code not PY_SSIZE_T_CLEAN will cause runtime failures with Python 3.10:

SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

Fixes Fedora Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1899117